GET http://localhost:3001/todos


###
POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Eat breakfast"
}
###
DELETE http://localhost:3001/todo/delete/64cd0479720b592f489ed5ea

###

GET http://localhost:3001/todo/complete/64cd0683e19b435f8dc2a3a3
